Login
AureumBox/Proyecto-IDS-Mobile pull request #1
Opened 2022-11-11 00:55 UTC by AureumBox

2022-11-11 01:46 UTC, HopeAero requested changes
Codigo espagueti en el login.js y en otras partes de funcionalidades en comentarios no implementadas, decidir si sera implementada o no

2022-11-18 01:38 UTC, Crismp02 approved these changes
Todo lo que haga mi madre está bello. La mejor Middleware <3

2022-11-21 04:50 UTC, AlejandroJRosas approved these changes

2022-11-22 02:36 UTC, Hector1567XD commented
> Codigo espagueti en el login.js y en otras partes de funcionalidades en comentarios no implementadas, decidir si sera implementada o no

👀

2022-11-23 03:33 UTC, GloodBuster approved these changes
Bien bello lo que esta ese Login/Registro

2022-11-23 03:42 UTC, luizzzito approved these changes
bien fino el front

2022-11-23 03:43 UTC, merged

2022-11-23 10:29 UTC, Hector1567XD commented
@AlejandroJRosas como ya se mergeo ya se puede borrar la rama ajrosas?