Merge middle front
AureumBox/Proyecto-IDS-Mobile pull request #10
Opened 2022-12-23 19:17 UTC by AlejandroJRosas

2022-12-23 20:03 UTC, AureumBox approved these changes

2022-12-23 20:18 UTC, Crismp02 approved these changes
Los megas mejores gastados de mi vida, se ve brutal!! Este equipazo se merece un premio

2022-12-26 17:19 UTC, GloodBuster approved these changes
Me salen el peso y la altura descuadrados pero supongo q tiene q ver con lo de apple y android, y al obtener cromos el carrusel no se actualiza hasta que haya una recarga, obviando esos detallitos esta bien bello

2022-12-26 17:23 UTC, AlejandroJRosas commented
> Me salen el peso y la altura descuadrados pero supongo q tiene q ver con lo de apple y android, y al obtener cromos el carrusel no se actualiza hasta que haya una recarga, obviando esos detallitos esta bien bello

Lo del peso y altura descuadrados se arregló en otra rama ya mergeada en Master así que listo, ya se coloca el hotfix de carrusel

2022-12-27 00:23 UTC, Hector1567XD requested changes

2022-12-27 00:23 UTC, Hector1567XD commented on src/components/HeaderComponent/index.js
> +    console.log("LE HAS DADO CLICK A UN ANUNCIO :D ", redirectUrl);
```suggestion
```

2022-12-27 00:23 UTC, Hector1567XD commented on src/components/HeaderComponent/index.js
> +      {/* <TouchableOpacity>
Remove commented code

2022-12-27 00:23 UTC, Hector1567XD commented on src/components/StickerTemplate.js
> +import jugador from "../../assets/appAssets/test/ksa/ksa_5.png"
Supongo que luego es ahora

2022-12-27 00:23 UTC, Hector1567XD commented on src/components/StickerTemplate.js
> +/* SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS */
```suggestion
import Constants from 'expo-constants';
```
Ya estamos en staging y este PR va a master, que falta para llegar a "online" xP?

2022-12-27 00:23 UTC, Hector1567XD commented on src/components/StickerTemplate.js
> +                        // source={jugador}
```suggestion
```

2022-12-27 00:23 UTC, Hector1567XD commented on src/components/StickerTemplate.js
> +                        source={{ uri: sticker.img }} //cambiar a activo cuando ya este la BD
```suggestion
                        source={{ uri: sticker.img }}
```
Hay que cambiar que 🤔 ?

2022-12-27 00:23 UTC, Hector1567XD commented on src/screens/BottomNavBar.js
> +                        } else if ((rn === 'AlbumNavigator')) {
El nombre "rn" es muy poco intuitivo, recomiendo cambiar a algo mas intuitivo
```suggestion
                        } else if ((routeName === 'AlbumNavigator')) {
```

2022-12-27 00:23 UTC, Hector1567XD commented on src/screens/BottomNavBar.js
>                          if (rn === 'Home') {
Recomendaría aqui usar un `switch` en lugar de múltiples IF´s, o... inclusive mejor! un diccionario / hash-map

2022-12-27 00:23 UTC, Hector1567XD commented on src/screens/homePageAuth/LogIn.js
> +                navigation.navigate(HPANavigation.BNB);
Que significa BNB?

2022-12-27 00:23 UTC, Hector1567XD commented on src/screens/homePageAuth/LogIn.js
>                  console.log(result.data.token)
Estamos exponiendo el token del usuario a algo que llegara a produccion D:
```suggestion
```
-- Pero Hector, es en su propia PC, expone su propio token
Si, pero es una mala practica
-- Por que
No se, pero se que tiene implicaciones de seguridad

2022-12-27 00:23 UTC, Hector1567XD commented on src/screens/homePageAuth/LogIn.js
>                  console.log(store.getState())
```suggestion
```
Nos parecemos a los de la ruleta-online

2022-12-27 00:23 UTC, Hector1567XD commented on src/screens/mainScreen/Album/Album.js
> +      alert("mami" + error.message);
ª
```suggestion
      alert(error.message);
```

2022-12-27 00:28 UTC, Hector1567XD requested changes

2022-12-27 00:28 UTC, Hector1567XD commented on src/screens/mainScreen/Album/AlbumPage/index.js
> +      console.log(data.actualProgressPercentage);
```suggestion
```

2022-12-27 00:28 UTC, Hector1567XD commented on src/screens/mainScreen/Fantasy.js
> +            {/* <StickerTemplate /> */}
```suggestion
```

2022-12-27 00:28 UTC, Hector1567XD commented on src/services/inventory.services.js
> +  console.log("mira album" + JSON.stringify(data)); */
```suggestion
```

2022-12-27 00:28 UTC, Hector1567XD commented on src/services/inventory.services.js
> +  // console.log(URL_INV + `/public-events/${eventId}/album`)
```suggestion
```

2022-12-27 00:28 UTC, Hector1567XD commented on src/services/inventory.services.js
> +  // console.log("mira stupido" + JSON.stringify(data));
```suggestion
```
Anda paya stupido

2022-12-27 00:28 UTC, Hector1567XD commented on src/services/inventory.services.js
> +  console.log(data);
```suggestion
```

2022-12-27 00:29 UTC, Hector1567XD commented on src/components/HeaderComponent/index.js
> +    console.log("LE HAS DADO CLICK A UN ANUNCIO :D ", redirectUrl);
Ahora que lo pienso, le corrigieron la ortografia a este console.log en el PR, pero no se les ocurrio borrar el console.log XD

2022-12-27 19:38 UTC, Noralgorithm approved these changes
lgtm

2022-12-27 21:45 UTC, AlejandroJRosas commented on src/screens/homePageAuth/LogIn.js
> +                navigation.navigate(HPANavigation.BNB);
Bottom Navigation Bar

2022-12-27 21:45 UTC, AlejandroJRosas commented on src/screens/BottomNavBar.js
>                          if (rn === 'Home') {
Ya esto se arreglo en otro commit

2022-12-27 21:45 UTC, AlejandroJRosas commented on src/components/StickerTemplate.js
> +/* SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS */
Ya se arreglo en otro commit

2022-12-27 21:45 UTC, AlejandroJRosas commented on src/components/StickerTemplate.js
> +import jugador from "../../assets/appAssets/test/ksa/ksa_5.png"
Ya se arreglo en otro commit

2022-12-27 22:27 UTC, merged